version: "2"
services:
  core0:
    image:  amacneil/bitcoin:0.13.2
    volumes: 
      - "./config/core0.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
  core1:
    image: amacneil/bitcoin:0.13.2
    volumes: 
      - "./config/core1.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
  bu0:
    image: amacneil/bitcoinunlimited:1.0.1.1
    volumes:
      - "./config/bu0.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
  bu1:
    image: amacneil/bitcoinunlimited:1.0.1.1
    volumes:
      - "./config/bu1.conf:/home/bitcoin/.bitcoin/bitcoin.conf"
  bitcore:
    image: sena/bitcore
    volumes:
      - "./config/bitcore.conf:/root/.bitcore/data/bitcoin.conf"
      - "./config/bitcore-node.json:/root/.bitcore/bitcore-node.json"
    ports:
      - "3001:3001" 
      - "18333:18333"
